apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: gpu
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ['g4dn.xlarge']
  taints:
    - key: nvidia.com/gpu
      value: 'true'
      effect: NoSchedule
  provider:
    instanceProfile: ${iam-instance-profile-id}
    subnetSelector:
       Name: "${eks-vpc_name}-private*"
    securityGroupSelector:
       karpenter.sh/discovery/${eks-cluster-id}: '${eks-cluster-id}'
  labels:
    type: karpenter
    provisioner: gpu
  ttlSecondsAfterEmpty: 60
