apiVersion: batch/v1
kind: Job
metadata:
  name: nvidia-bash-job
spec:
  template:
    spec:
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        provisioner: "gpu"
      containers:
      - name: nvidia
        image: nvidia/cuda:12.2.0-devel-ubuntu20.04
        command: ["bash", "-c", "while true; do sleep 3600; done"]
      restartPolicy: Never
  backoffLimit: 0
  completions: 1
  ttlSecondsAfterFinished: 600

